name: Checkstyle Check

on:
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Fail if Checkstyle violations are found
        if: failure()
        run: exit 1
